### ISSUE TITLE
Development Setup

### ISSUE THREAD

**Issue by kmaneesh** [sgmonusg/stock#1]
First lets create a replicable development setup.
- Init Git Repo
- Add a README.md
- Add a Vagrant File and provision for booting a ubuntu based (1GB system) which will be development env for the project. Look at my Vagrant-R Repo and read about vagrant and provision.
- List out the tool stack which will be used for the project.

Close the issue when the Vagrant setup runs without issue on your Windows Laptop. (I assume you are using Windows)

Lets make this repo a public repo.

Please note the Vagrant-R repo used the ansible you do not need to use ansible. You can use the shell script to do the provision.

**Comment by kmaneesh** [comment]
I have added some template code for you to move ahead.

**Comment by sgmonusg** [comment]
![image](https://cloud.githubusercontent.com/assets/11517226/15664151/30416c62-271f-11e6-905b-864a2fbce8f3.png)
uncle reached here what should i do next 
@kmaneesh
